os: linux
dist: focal
sudo: required
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.14.2-focal
  - sudo apt-get update -qq
  - sudo apt-get install -y libmicrohttpd-dev libpulse-dev freeglut3-dev
  - sudo apt-get install qt514-meta-full
  - source /opt/qt514/bin/qt514-env.sh

env:
  - CMAKE=$(which cmake)

branches:
  only:
  - dev
  - master

script:
  - make -C build modules 
  - sudo make -C modules/guidolib/build CMAKE=$CMAKE install 
  - sudo make -C modules/libmusicxml/build CMAKE=$CMAKE install
  - make -C build inscore
